// Full archetype profiles — innate behavioral wiring mapped to trading alignment
export const ARCHETYPE_DETAILS = [
  {
    name: "The Precision Striker",
    tagline: "Hardwired for selectivity — waits patiently, strikes rarely, wins often",
    style: "Swing trading with strict criteria, low frequency",
    timeframe: "Days to weeks",
    sizing: "2–3% per position",
    strength: "Exceptional win rate from innate selectivity — your wiring naturally filters out low-quality setups",
    risk: "Missing opportunities due to excessive selectivity; can go weeks without a trade",
    coaching: "Your selectivity is hardwired — don't fight it. Instead, expand your watchlist so your natural filter has more to work with.",
    scores: { RT: 3.2, ED: 8.5, EV: 2.4, AA: 7.8, TH: 5.5, CI: 5.8, AQ: 2.6, SO: 3.0, TS: 5.5 },
  },
  {
    name: "The Systematic",
    tagline: "Innately rules-driven — emotionally flat, mechanically precise",
    style: "Algorithmic or mechanical systems trading",
    timeframe: "Variable — system-dependent",
    sizing: "3–5% per position",
    strength: "Your natural wiring eliminates emotional trading errors through an innate need for process and structure",
    risk: "Over-optimization; inability to handle discretionary situations that fall outside the system",
    coaching: "Build systems that adapt to regime changes. Your wiring craves structure — make sure the structure itself can evolve.",
    scores: { RT: 5.0, ED: 9.0, EV: 2.0, AA: 5.5, TH: 5.5, CI: 5.0, AQ: 4.5, SO: 3.5, TS: 7.0 },
  },
  {
    name: "The Blitz Trader",
    tagline: "Wired for speed, intensity, and decisive action under pressure",
    style: "Day trading momentum and breakout strategies",
    timeframe: "Minutes to hours",
    sizing: "1–3% per position (hard cap required)",
    strength: "Your nervous system is built for high-stimulus environments — you capture moves slower traders can't",
    risk: "Blowup risk is extremely high — your wiring needs hard external guardrails enforced by platform settings",
    coaching: "External accountability and position size limits are non-negotiable. Your wiring won't self-regulate here — build the cage first, then trade inside it.",
    scores: { RT: 8.5, ED: 2.5, EV: 8.0, AA: 7.5, TH: 1.8, CI: 7.5, AQ: 8.0, SO: 4.0, TS: 8.5 },
  },
  {
    name: "The Thesis Builder",
    tagline: "Naturally deep-thinking — builds conviction through research, not impulse",
    style: "Fundamental analysis with multi-month holding periods",
    timeframe: "Weeks to months",
    sizing: "3–5% per position",
    strength: "Your innate analytical depth catches what surface-level traders miss; wired for thorough, patient research",
    risk: "Holding losers too long; opportunity cost blindness from over-research before entry",
    coaching: "Define clear invalidation criteria BEFORE entering. Your wiring wants to keep researching — set a deadline and honor it.",
    scores: { RT: 5.0, ED: 5.5, EV: 2.5, AA: 8.0, TH: 7.5, CI: 7.5, AQ: 4.0, SO: 3.0, TS: 6.0 },
  },
  {
    name: "The Steward",
    tagline: "Innately protective — hardwired for preservation over speculation",
    style: "Passive investing with tactical overlays",
    timeframe: "Months to years",
    sizing: "1–2% per position",
    strength: "Your wiring survives drawdowns that destroy aggressive traders — capital preservation is your nature",
    risk: "Underperformance due to excessive caution; you may not need to actively trade at all",
    coaching: "Your protective instinct is innate — don't fight it by forcing active trading. Optimize asset allocation instead.",
    scores: { RT: 2.0, ED: 7.0, EV: 5.0, AA: 3.0, TH: 8.0, CI: 3.0, AQ: 3.0, SO: 5.5, TS: 4.5 },
  },
  {
    name: "The Chameleon",
    tagline: "Naturally adaptive — wired to read and shift with changing conditions",
    style: "Multi-strategy approach matching current environment",
    timeframe: "Variable — condition-dependent",
    sizing: "2–4% per position",
    strength: "Your innate adaptability lets you thrive across different market environments where rigid traders fail",
    risk: "Jack of all trades, master of none — your wiring pulls you toward novelty before achieving depth",
    coaching: "Develop 2–3 core strategies to mastery before expanding. Your wiring wants variety — channel it, don't suppress it.",
    scores: { RT: 5.0, ED: 5.0, EV: 5.0, AA: 5.0, TH: 5.0, CI: 5.0, AQ: 8.5, SO: 5.5, TS: 6.0 },
  },
  {
    name: "The Contrarian",
    tagline: "Hardwired to think independently — buys when others sell, holds through fear",
    style: "Deep value, crisis investing, mean reversion",
    timeframe: "Weeks to months",
    sizing: "3–5% per position",
    strength: "Your innate independence and conviction let you capture major reversals that consensus traders miss",
    risk: "Catching falling knives; being early is indistinguishable from being wrong",
    coaching: "Distinguish between conviction and stubbornness with data-driven invalidation checkpoints. Your wiring holds — give it clear exit rules.",
    scores: { RT: 7.5, ED: 5.5, EV: 2.5, AA: 8.5, TH: 7.5, CI: 8.5, AQ: 2.5, SO: 2.0, TS: 6.5 },
  },
  {
    name: "The Current Rider",
    tagline: "Naturally attuned to flow — wired to move with momentum, not against it",
    style: "Trend following, momentum strategies, moving average systems",
    timeframe: "Days to weeks",
    sizing: "2–4% per position",
    strength: "Your wiring captures the meat of trends without fighting the market — low-stress when aligned with flow",
    risk: "Whipsawing in choppy markets; late entries and exits during trend transitions",
    coaching: "Develop filters for trending vs. range-bound conditions. Your wiring follows — give it a clear signal of what to follow.",
    scores: { RT: 5.0, ED: 5.5, EV: 4.5, AA: 3.5, TH: 5.0, CI: 4.5, AQ: 7.0, SO: 6.0, TS: 5.5 },
  },
  {
    name: "The Rapid Fire",
    tagline: "Wired for speed and volume — innately needs rapid feedback loops",
    style: "Scalping, high-frequency manual trading",
    timeframe: "Seconds to minutes",
    sizing: "1–2% per position",
    strength: "Many at-bats per day; your wiring cuts losses fast and iterates rapidly",
    risk: "Emotional exhaustion, commission drag, overtrading, burnout",
    coaching: "Strict daily loss limits and mandatory screen breaks. Your wiring wants constant action — build in forced pauses.",
    scores: { RT: 5.5, ED: 7.0, EV: 7.5, AA: 5.0, TH: 1.5, CI: 2.5, AQ: 7.5, SO: 4.0, TS: 8.0 },
  },
  {
    name: "The Engineer",
    tagline: "Innately analytical — hardwired to build structured, defined-risk positions",
    style: "Options strategies — spreads, iron condors, calendars",
    timeframe: "Days to weeks",
    sizing: "2–3% per position",
    strength: "Your wiring demands precisely defined risk/reward — this naturally suits multi-leg strategies",
    risk: "Over-complexity; analysis paralysis; missing simpler opportunities while engineering the perfect setup",
    coaching: "Simplify where possible — complexity does not equal edge. Your wiring loves to build — focus that energy on 2-leg strategies first.",
    scores: { RT: 3.0, ED: 8.0, EV: 2.5, AA: 8.0, TH: 6.5, CI: 5.0, AQ: 4.5, SO: 2.5, TS: 7.0 },
  },
  {
    name: "The Wildcard",
    tagline: "Innately unconventional — wired to find angles nobody else sees",
    style: "Event-driven, special situations, asymmetric bets",
    timeframe: "Variable — event-dependent",
    sizing: "1–3% per position (hard cap required)",
    strength: "Your wiring finds opportunities others can't see; naturally drawn to asymmetric payoffs",
    risk: "Spectacular blowups when innate conviction meets innate impulsiveness — this combination needs guardrails",
    coaching: "Create one non-negotiable rule: maximum position size. Period. Your wiring won't self-limit — make the limit external.",
    scores: { RT: 8.0, ED: 2.0, EV: 5.5, AA: 8.5, TH: 2.5, CI: 7.5, AQ: 8.0, SO: 3.5, TS: 6.5 },
  },
  {
    name: "The Steady Hand",
    tagline: "Wired for caution with deep emotional awareness — protects capital through vigilance",
    style: "Income strategies — dividends, covered calls, bonds",
    timeframe: "Months to years",
    sizing: "1–2% per position",
    strength: "Consistent income generation; your innate caution produces low drawdowns and sustainable returns",
    risk: "Never generating meaningful returns; paralysis during volatility from high emotional sensitivity",
    coaching: "Your wiring feels the market deeply but values safety. Use that awareness as a signal, not a cage. Small defined-risk positions build confidence.",
    scores: { RT: 2.5, ED: 5.5, EV: 6.5, AA: 3.0, TH: 7.5, CI: 3.0, AQ: 6.5, SO: 7.0, TS: 4.5 },
  },
  {
    name: "The Momentum Chaser",
    tagline: "Wired for excitement and social energy — naturally drawn to what's moving",
    style: "Momentum-driven entries — often enters after the initial move",
    timeframe: "Hours to days",
    sizing: "Needs hard caps — innate tendency to oversize on excitement",
    strength: "High energy and natural market awareness; your wiring senses what's moving before most",
    risk: "Buying tops, panic selling bottoms, emotional whipsaw — your wiring needs the most external structure",
    coaching: "Your wiring is reactive, not broken. Mandatory waiting period before entries. Journal every impulse to build pattern awareness.",
    scores: { RT: 7.0, ED: 2.0, EV: 8.5, AA: 2.0, TH: 2.0, CI: 2.5, AQ: 7.0, SO: 8.0, TS: 5.0 },
  },
  {
    name: "The Conviction Holder",
    tagline: "Hardwired for deep commitment — once convinced, nearly unshakeable",
    style: "High-conviction position trading, long-term thesis plays",
    timeframe: "Months to years",
    sizing: "3–5% per position",
    strength: "Your innate persistence captures major thesis plays that require surviving significant adversity",
    risk: "Holding losers far too long; your innate stubbornness can disguise itself as conviction",
    coaching: "Pre-commit to invalidation criteria before every entry. Your wiring holds — give it clear, data-driven exit rules written in advance.",
    scores: { RT: 6.0, ED: 5.0, EV: 3.5, AA: 6.5, TH: 8.5, CI: 9.5, AQ: 2.0, SO: 3.0, TS: 6.0 },
  },
  {
    name: "The Networked Trader",
    tagline: "Innately collaborative — wired to process and decide through community",
    style: "Community-based trading, signal following, collaborative analysis",
    timeframe: "Variable — follows source",
    sizing: "2–3% per position",
    strength: "Your wiring benefits from collective wisdom; multiple perspectives reduce blind spots naturally",
    risk: "No independent edge; collapses when sources fail; innate social dependence amplifies herd behavior",
    coaching: "Gradually build independent analysis skill. Your wiring processes socially — that's fine, but develop one strategy you can execute alone.",
    scores: { RT: 4.0, ED: 4.5, EV: 5.5, AA: 1.5, TH: 4.5, CI: 3.0, AQ: 5.5, SO: 9.0, TS: 4.5 },
  },
  {
    name: "The Professional",
    tagline: "Rare balanced wiring — naturally combines risk-taking with discipline",
    style: "Multi-strategy with strong risk management overlay",
    timeframe: "Days to weeks",
    sizing: "3–5% per position",
    strength: "Your innate profile is one of the rarest — disciplined risk-taking is hardwired, not learned",
    risk: "May lack the extreme conviction needed for outsized returns; balanced wiring can mean balanced (not exceptional) results",
    coaching: "Identify which dimension to lean into for your specific market. Your wiring is balanced — choose when to let one trait dominate.",
    scores: { RT: 6.5, ED: 7.5, EV: 3.5, AA: 7.0, TH: 6.0, CI: 6.5, AQ: 6.0, SO: 4.5, TS: 7.5 },
  },
  {
    name: "The Analyst",
    tagline: "Innately data-driven — wired to need complete information before acting",
    style: "Quantitative analysis, fundamental deep-dives, systematic screening",
    timeframe: "Weeks to months",
    sizing: "2–3% per position",
    strength: "Your wiring produces thorough, well-researched positions; you're rarely caught off-guard by fundamentals",
    risk: "Analysis paralysis; your innate need for completeness makes you miss time-sensitive opportunities",
    coaching: "Set a research deadline for every opportunity. Your wiring wants more data — give it a time limit, not more data.",
    scores: { RT: 3.5, ED: 6.5, EV: 2.5, AA: 7.0, TH: 6.5, CI: 5.5, AQ: 3.5, SO: 3.5, TS: 5.5 },
  },
  {
    name: "The Sentinel",
    tagline: "Wired for balanced awareness — naturally defensive with steady composure",
    style: "Hedged positions, risk-parity, balanced portfolio approach",
    timeframe: "Weeks to months",
    sizing: "2–3% per position",
    strength: "Your wiring excels at protecting capital during downturns; innately steady and predictable",
    risk: "Over-hedging eats into returns; your natural caution may cause you to miss strong bull runs",
    coaching: "Define when to remove hedges. Your innate protection instinct has a cost — track it explicitly.",
    scores: { RT: 3.5, ED: 6.5, EV: 4.5, AA: 5.0, TH: 6.5, CI: 5.0, AQ: 5.0, SO: 5.0, TS: 6.0 },
  },
  {
    name: "The Pack Trader",
    tagline: "Innately social — wired to thrive through shared analysis and group energy",
    style: "Social/community-based trading, idea sharing, collaborative analysis",
    timeframe: "Variable — group-dependent",
    sizing: "2–3% per position",
    strength: "Your wiring creates a strong network effect; multiple perspectives reduce blind spots naturally",
    risk: "Groupthink amplifies bad trades; your wiring struggles when isolated from the group",
    coaching: "Develop one strategy you can execute alone. Your community is an input, not your trading plan — your wiring needs both.",
    scores: { RT: 5.0, ED: 4.5, EV: 5.5, AA: 2.5, TH: 4.5, CI: 4.5, AQ: 5.5, SO: 9.0, TS: 5.5 },
  },
  {
    name: "The Resilient",
    tagline: "Wired for intensity and recovery — falls hard, gets back up harder",
    style: "High-risk/high-reward with improving discipline over time",
    timeframe: "Variable — evolving",
    sizing: "Start at 1–2%, earn the right to increase",
    strength: "Your innate resilience means you keep showing up — this wiring has the highest long-term growth ceiling",
    risk: "Repeated drawdowns before lessons translate into systems; high emotional cost of the learning curve",
    coaching: "Your biggest innate asset is that you keep coming back. Channel that hardwired resilience into building a system. Journal religiously.",
    scores: { RT: 7.5, ED: 3.5, EV: 7.0, AA: 5.5, TH: 3.5, CI: 6.0, AQ: 7.5, SO: 5.5, TS: 7.0 },
  },
];
