// Full archetype profiles with descriptions, sample scores, and trading details
export const ARCHETYPE_DETAILS = [
  {
    name: "The Precision Striker",
    tagline: "Waits patiently for perfect setups, takes few trades but high-conviction",
    style: "Swing trading with strict criteria, low frequency",
    timeframe: "Days to weeks",
    sizing: "2–3% per position",
    strength: "Exceptional win rate from selectivity — avoids low-quality setups entirely",
    risk: "Missing opportunities due to excessive selectivity; can go weeks without a trade",
    coaching: "Expand your strike zone slightly without abandoning standards. Track missed setups that would have worked.",
    scores: { RT: 3.2, ED: 8.5, EV: 2.4, AA: 7.8, TH: 5.5, CI: 5.8, AQ: 2.6, SO: 3.0, TS: 5.5 },
  },
  {
    name: "The Systematic",
    tagline: "Rules-based, emotionally flat, mechanical execution",
    style: "Algorithmic or mechanical systems trading",
    timeframe: "Variable — system-dependent",
    sizing: "3–5% per position",
    strength: "Eliminates emotional trading errors almost entirely through process adherence",
    risk: "Over-optimization; inability to handle discretionary situations that fall outside the system",
    coaching: "Build systems that adapt to regime changes. Don't confuse backtested perfection with real-world edge.",
    scores: { RT: 5.0, ED: 9.0, EV: 2.0, AA: 5.5, TH: 5.5, CI: 5.0, AQ: 4.5, SO: 3.5, TS: 7.0 },
  },
  {
    name: "The Blitz Trader",
    tagline: "Aggressive, fast, high-conviction, high-volume",
    style: "Day trading momentum and breakout strategies",
    timeframe: "Minutes to hours",
    sizing: "1–3% per position (hard cap required)",
    strength: "Captures explosive moves that slower traders miss; thrives in high-volatility sessions",
    risk: "Blowup risk is extremely high — needs hard external risk limits enforced by platform settings",
    coaching: "External accountability and position size limits are non-negotiable. Max daily loss limit mandatory.",
    scores: { RT: 8.5, ED: 2.5, EV: 8.0, AA: 7.5, TH: 1.8, CI: 7.5, AQ: 8.0, SO: 4.0, TS: 8.5 },
  },
  {
    name: "The Thesis Builder",
    tagline: "Deep-research driven, builds multi-layer conviction before acting",
    style: "Fundamental analysis with multi-month holding periods",
    timeframe: "Weeks to months",
    sizing: "3–5% per position",
    strength: "Thorough analysis catches what surface-level traders miss; strong risk-adjusted returns",
    risk: "Holding losers too long; opportunity cost blindness from over-research before entry",
    coaching: "Define clear invalidation criteria BEFORE entering positions. Set time-based review triggers.",
    scores: { RT: 5.0, ED: 5.5, EV: 2.5, AA: 8.0, TH: 7.5, CI: 7.5, AQ: 4.0, SO: 3.0, TS: 6.0 },
  },
  {
    name: "The Steward",
    tagline: "Conservative, protective, buy-and-hold with guardrails",
    style: "Passive investing with tactical overlays",
    timeframe: "Months to years",
    sizing: "1–2% per position",
    strength: "Survives drawdowns that destroy aggressive traders; strong capital preservation",
    risk: "Underperformance due to excessive caution; may not need to actively trade at all",
    coaching: "Optimize asset allocation instead of chasing active trading. Small defined-risk positions build confidence.",
    scores: { RT: 2.0, ED: 7.0, EV: 5.0, AA: 3.0, TH: 8.0, CI: 3.0, AQ: 3.0, SO: 5.5, TS: 4.5 },
  },
  {
    name: "The Chameleon",
    tagline: "Adapts approach to market conditions, regime-aware",
    style: "Multi-strategy approach matching current environment",
    timeframe: "Variable — condition-dependent",
    sizing: "2–4% per position",
    strength: "Thrives across different market environments; never trapped in one approach",
    risk: "Jack of all trades, master of none — never achieves depth in any single strategy",
    coaching: "Develop 2–3 core strategies to mastery before expanding. Depth beats breadth.",
    scores: { RT: 5.0, ED: 5.0, EV: 5.0, AA: 5.0, TH: 5.0, CI: 5.0, AQ: 8.5, SO: 5.5, TS: 6.0 },
  },
  {
    name: "The Contrarian",
    tagline: "Buys when others sell, holds through extreme adversity",
    style: "Deep value, crisis investing, mean reversion",
    timeframe: "Weeks to months",
    sizing: "3–5% per position",
    strength: "Captures major reversals that consensus traders miss entirely",
    risk: "Catching falling knives; being early is indistinguishable from being wrong",
    coaching: "Distinguish between conviction and stubbornness with data-driven invalidation checkpoints.",
    scores: { RT: 7.5, ED: 5.5, EV: 2.5, AA: 8.5, TH: 7.5, CI: 8.5, AQ: 2.5, SO: 2.0, TS: 6.5 },
  },
  {
    name: "The Current Rider",
    tagline: "Follows trends and momentum, goes with market flow",
    style: "Trend following, momentum strategies, moving average systems",
    timeframe: "Days to weeks",
    sizing: "2–4% per position",
    strength: "Captures the meat of trends without fighting the market; low-stress when trending",
    risk: "Whipsawing in choppy markets; late entries and exits during trend transitions",
    coaching: "Develop filters for trending vs. range-bound conditions. Have a different playbook for chop.",
    scores: { RT: 5.0, ED: 5.5, EV: 4.5, AA: 3.5, TH: 5.0, CI: 4.5, AQ: 7.0, SO: 6.0, TS: 5.5 },
  },
  {
    name: "The Rapid Fire",
    tagline: "Quick in and out, rapid-fire small gains, high volume",
    style: "Scalping, high-frequency manual trading",
    timeframe: "Seconds to minutes",
    sizing: "1–2% per position",
    strength: "Many at-bats per day; fast loss-cutting; rapid iteration and learning",
    risk: "Emotional exhaustion, commission drag, overtrading, burnout",
    coaching: "Strict daily loss limits and mandatory screen breaks. Track cost-per-trade drag.",
    scores: { RT: 5.5, ED: 7.0, EV: 7.5, AA: 5.0, TH: 1.5, CI: 2.5, AQ: 7.5, SO: 4.0, TS: 8.0 },
  },
  {
    name: "The Engineer",
    tagline: "Builds complex, multi-leg positions with defined risk",
    style: "Options strategies — spreads, iron condors, calendars",
    timeframe: "Days to weeks",
    sizing: "2–3% per position",
    strength: "Precisely defined risk/reward on every trade; income generation in sideways markets",
    risk: "Over-complexity; analysis paralysis; missing simpler opportunities while engineering perfect setups",
    coaching: "Simplify where possible — complexity does not equal edge. Start with 2-leg strategies.",
    scores: { RT: 3.0, ED: 8.0, EV: 2.5, AA: 8.0, TH: 6.5, CI: 5.0, AQ: 4.5, SO: 2.5, TS: 7.0 },
  },
  {
    name: "The Wildcard",
    tagline: "Unconventional, breaks rules, finds unique angles",
    style: "Event-driven, special situations, asymmetric bets",
    timeframe: "Variable — event-dependent",
    sizing: "1–3% per position (hard cap required)",
    strength: "Finds opportunities others can't see; captures asymmetric payoffs",
    risk: "Spectacular blowups when conviction meets poor discipline; inconsistency",
    coaching: "Create one non-negotiable rule: maximum position size. Period. Everything else is secondary.",
    scores: { RT: 8.0, ED: 2.0, EV: 5.5, AA: 8.5, TH: 2.5, CI: 7.5, AQ: 8.0, SO: 3.5, TS: 6.5 },
  },
  {
    name: "The Steady Hand",
    tagline: "Cautious, community-influenced, protective of capital",
    style: "Income strategies — dividends, covered calls, bonds",
    timeframe: "Months to years",
    sizing: "1–2% per position",
    strength: "Consistent income generation; low drawdowns; sustainable long-term approach",
    risk: "Never generating meaningful returns; paralysis during volatility",
    coaching: "Gradually expand comfort zone with small, defined-risk positions to build confidence.",
    scores: { RT: 2.5, ED: 5.5, EV: 6.5, AA: 3.0, TH: 7.5, CI: 3.0, AQ: 6.5, SO: 7.0, TS: 4.5 },
  },
  {
    name: "The FOMO Chaser",
    tagline: "Reactive, emotionally driven, chases momentum after the move",
    style: "Momentum chasing — often enters late and exits too early or too late",
    timeframe: "Hours to days",
    sizing: "Needs hard caps — tendency to oversize on excitement",
    strength: "High energy and market awareness; strong instinct for what's moving",
    risk: "Buying tops, panic selling bottoms, emotional whipsaw; the profile most likely to lose money",
    coaching: "This profile needs the most work. Mandatory waiting period before entries. Journal every impulse trade.",
    scores: { RT: 7.0, ED: 2.0, EV: 8.5, AA: 2.0, TH: 2.0, CI: 2.5, AQ: 7.0, SO: 8.0, TS: 5.0 },
  },
  {
    name: "The Diamond Hand",
    tagline: "Near-unshakeable once committed, holds through everything",
    style: "High-conviction position trading, long-term thesis plays",
    timeframe: "Months to years",
    sizing: "3–5% per position",
    strength: "Captures major thesis plays that require surviving significant adversity",
    risk: "Holding losers far too long; stubbornness disguised as conviction; inability to admit being wrong",
    coaching: "Pre-commit to invalidation criteria. Schedule mandatory thesis reviews at fixed intervals.",
    scores: { RT: 6.0, ED: 5.0, EV: 3.5, AA: 6.5, TH: 8.5, CI: 9.5, AQ: 2.0, SO: 3.0, TS: 6.0 },
  },
  {
    name: "The Copy Trader",
    tagline: "Follows proven traders and systems, community-dependent",
    style: "Mirror trading, signal following, community-based entries",
    timeframe: "Variable — follows source",
    sizing: "2–3% per position",
    strength: "Benefits from collective wisdom; low analysis burden; can be profitable if sources are good",
    risk: "No independent edge; collapses when sources go wrong; herd behavior amplifies losses",
    coaching: "Gradually build independent analysis skill. Start logging your own calls alongside the signals you follow.",
    scores: { RT: 4.0, ED: 4.5, EV: 5.5, AA: 1.5, TH: 4.5, CI: 3.0, AQ: 5.5, SO: 9.0, TS: 4.5 },
  },
  {
    name: "The Professional",
    tagline: "Balanced across all dimensions, high discipline, controlled risk",
    style: "Multi-strategy with strong risk management overlay",
    timeframe: "Days to weeks",
    sizing: "3–5% per position",
    strength: "Rare profile — combines risk-taking with discipline; sustainable edge across regimes",
    risk: "May lack the extreme conviction needed for outsized returns; too balanced to be exceptional",
    coaching: "Identify which dimension to lean into for your specific market. Perfection can be the enemy of profit.",
    scores: { RT: 6.5, ED: 7.5, EV: 3.5, AA: 7.0, TH: 6.0, CI: 6.5, AQ: 6.0, SO: 4.5, TS: 7.5 },
  },
  {
    name: "The Analyst",
    tagline: "Data-driven, research-heavy, needs complete information before acting",
    style: "Quantitative analysis, fundamental deep-dives, systematic screening",
    timeframe: "Weeks to months",
    sizing: "2–3% per position",
    strength: "Thorough, well-researched positions; rarely caught off-guard by fundamentals",
    risk: "Analysis paralysis; misses time-sensitive opportunities; over-optimizes entry points",
    coaching: "Set a research deadline for every opportunity. If you haven't acted in 48 hours, make a decision.",
    scores: { RT: 3.5, ED: 6.5, EV: 2.5, AA: 7.0, TH: 6.5, CI: 5.5, AQ: 3.5, SO: 3.5, TS: 5.5 },
  },
  {
    name: "The Sentinel",
    tagline: "Balanced risk awareness, steady, defensive first mindset",
    style: "Hedged positions, risk-parity, balanced portfolio approach",
    timeframe: "Weeks to months",
    sizing: "2–3% per position",
    strength: "Excellent at protecting capital during downturns; steady, predictable returns",
    risk: "Over-hedging eats into returns; may miss strong bull runs from excessive caution",
    coaching: "Define when to remove hedges. Protection has a cost — track it explicitly.",
    scores: { RT: 3.5, ED: 6.5, EV: 4.5, AA: 5.0, TH: 6.5, CI: 5.0, AQ: 5.0, SO: 5.0, TS: 6.0 },
  },
  {
    name: "The Pack Trader",
    tagline: "Thrives in community, shares ideas, trades with the group",
    style: "Social/community-based trading, idea sharing, collaborative analysis",
    timeframe: "Variable — group-dependent",
    sizing: "2–3% per position",
    strength: "Strong network effect; multiple perspectives reduce blind spots; accountability built in",
    risk: "Groupthink amplifies bad trades; struggles when isolated; herd behavior during panic",
    coaching: "Develop one strategy you can execute alone. Your community is an input, not your trading plan.",
    scores: { RT: 5.0, ED: 4.5, EV: 5.5, AA: 2.5, TH: 4.5, CI: 4.5, AQ: 5.5, SO: 9.0, TS: 5.5 },
  },
  {
    name: "The Phoenix",
    tagline: "Recovers from blowups, learns from failure, keeps coming back",
    style: "High-risk/high-reward with improving discipline over time",
    timeframe: "Variable — evolving",
    sizing: "Start at 1–2%, earn the right to increase",
    strength: "Resilience and growth mindset; each failure builds better habits; ultimate long-term potential",
    risk: "Repeated blowups before lessons stick; high emotional cost of the learning curve",
    coaching: "Your biggest asset is that you keep showing up. Now channel that energy into a system. Journal religiously.",
    scores: { RT: 7.5, ED: 3.5, EV: 7.0, AA: 5.5, TH: 3.5, CI: 6.0, AQ: 7.5, SO: 5.5, TS: 7.0 },
  },
];
