export const C = {
  accent: "#00E5A0",
  accentDim: "#00E5A040",
  accentGlow: "#00E5A018",
  red: "#E63946",
  blue: "#457B9D",
  orange: "#F4A261",
  green: "#2A9D8F",
  purple: "#9B5DE5",
  pink: "#F15BB5",
  cyan: "#00BBF9",
  yellow: "#EAB308",
  teal: "#14B8A6",
  burnt: "#D97706",
  lime: "#7CB518",
  bg: "#050A0F",
  bgCard: "#0A1118",
  bgHover: "#0F1A24",
  border: "#1A2A3A",
  borderLit: "#2A3A4A",
  text: "#E8EDF2",
  dim: "#6B8299",
  muted: "#3A5068",
};

export const MONO = "'JetBrains Mono', 'Fira Code', monospace";
export const SANS = "'Outfit', system-ui, sans-serif";

export const DIMS = [
  { key: "RT", name: "Risk Temperament", color: C.red, lo: "Risk Averse", hi: "Risk Seeking", desc: "Your hardwired relationship with uncertainty and potential loss — how your nervous system responds to risk, not what you think about it intellectually. Stable from early childhood." },
  { key: "ED", name: "Execution Discipline", color: C.blue, lo: "Impulsive", hi: "Systematic", desc: "Your innate tendency toward structure, rules, and process adherence. The child who made their bed every morning is the adult who follows their trading plan." },
  { key: "EV", name: "Emotional Velocity", color: C.orange, lo: "Slow/Muted", hi: "Fast/Intense", desc: "The speed, intensity, and duration of your emotional responses. This is hardwired nervous system reactivity — not something you can train away." },
  { key: "AA", name: "Analytical Autonomy", color: C.green, lo: "Consensus-Driven", hi: "Independent", desc: "Your natural tendency to form independent conclusions versus seeking external validation. The child who questioned authority is the adult contrarian trader." },
  { key: "TH", name: "Time Horizon", color: C.purple, lo: "Instant Feedback", hi: "Infinite Patience", desc: "Your innate tolerance for delayed gratification. Research shows this is measurable by age 4 and predicts behavior decades later." },
  { key: "CI", name: "Conviction Intensity", color: C.pink, lo: "Easily Shaken", hi: "Unshakeable", desc: "The strength with which you hold to a position under pressure. This is innate persistence — the 'won't back down' trait you've carried since childhood." },
  { key: "AQ", name: "Adaptability Quotient", color: C.cyan, lo: "Fixed/Rigid", hi: "Fluid/Evolving", desc: "Your innate openness to change and new approaches. Some children naturally explore and experiment; others specialize and deepen. This pattern persists for life." },
  { key: "SO", name: "Social Orientation", color: C.burnt, lo: "Solo Processor", hi: "Social Processor", desc: "Whether you process best alone or through conversation. Introversion and extraversion are among the most stable traits across the entire lifespan." },
  { key: "TS", name: "Drive Capacity", color: C.lime, lo: "Quick Fatigue", hi: "Endless Energy", desc: "Your innate energy reserves and recovery speed under sustained cognitive load. Some people are naturally higher-energy from birth — this doesn't change." },
];

export const ARCHETYPES = [
  { name: "The Precision Striker", color: C.red },
  { name: "The Systematic", color: C.blue },
  { name: "The Blitz Trader", color: C.orange },
  { name: "The Thesis Builder", color: C.teal },
  { name: "The Steward", color: C.purple },
  { name: "The Chameleon", color: C.cyan },
  { name: "The Contrarian", color: C.pink },
  { name: "The Current Rider", color: C.green },
  { name: "The Rapid Fire", color: C.yellow },
  { name: "The Engineer", color: "#6366F1" },
  { name: "The Wildcard", color: C.red },
  { name: "The Steady Hand", color: C.teal },
  { name: "The Momentum Chaser", color: C.orange },
  { name: "The Conviction Holder", color: C.purple },
  { name: "The Networked Trader", color: C.cyan },
  { name: "The Professional", color: C.green },
  { name: "The Analyst", color: C.blue },
  { name: "The Sentinel", color: C.lime },
  { name: "The Pack Trader", color: C.burnt },
  { name: "The Resilient", color: C.red },
];
