export const C = {
  accent: "#00E5A0",
  accentDim: "#00E5A040",
  accentGlow: "#00E5A018",
  red: "#E63946",
  blue: "#457B9D",
  orange: "#F4A261",
  green: "#2A9D8F",
  purple: "#9B5DE5",
  pink: "#F15BB5",
  cyan: "#00BBF9",
  yellow: "#EAB308",
  teal: "#14B8A6",
  burnt: "#D97706",
  lime: "#7CB518",
  bg: "#050A0F",
  bgCard: "#0A1118",
  bgHover: "#0F1A24",
  border: "#1A2A3A",
  borderLit: "#2A3A4A",
  text: "#E8EDF2",
  dim: "#6B8299",
  muted: "#3A5068",
};

export const MONO = "'JetBrains Mono', 'Fira Code', monospace";
export const SANS = "'Outfit', system-ui, sans-serif";

export const DIMS = [
  { key: "RT", name: "Risk Temperament", color: C.red, lo: "Risk Averse", hi: "Risk Seeking", icon: "⚡", desc: "Innate comfort with uncertainty and potential loss" },
  { key: "ED", name: "Execution Discipline", color: C.blue, lo: "Impulsive", hi: "Systematic", icon: "🎯", desc: "Ability to follow rules and systems under pressure" },
  { key: "EV", name: "Emotional Velocity", color: C.orange, lo: "Slow/Muted", hi: "Fast/Intense", icon: "💥", desc: "Speed and intensity of emotional response" },
  { key: "AA", name: "Analytical Autonomy", color: C.green, lo: "Consensus-Driven", hi: "Independent", icon: "🧠", desc: "Independence of thought vs. reliance on others" },
  { key: "TH", name: "Time Horizon", color: C.purple, lo: "Instant Feedback", hi: "Infinite Patience", icon: "⏳", desc: "Natural tolerance for delayed gratification" },
  { key: "CI", name: "Conviction Intensity", color: C.pink, lo: "Easily Shaken", hi: "Unshakeable", icon: "💎", desc: "Strength of commitment under adversity" },
  { key: "AQ", name: "Adaptability Quotient", color: C.cyan, lo: "Fixed/Rigid", hi: "Fluid/Evolving", icon: "🔄", desc: "Willingness to change when evidence demands" },
  { key: "SO", name: "Social Orientation", color: C.burnt, lo: "Solo Processor", hi: "Social Processor", icon: "👥", desc: "Whether you think best alone or through conversation" },
  { key: "TS", name: "Trading Stamina", color: C.lime, lo: "Quick Fatigue", hi: "Endless Energy", icon: "🔋", desc: "Sustained focus and recovery speed under stress" },
];

export const ARCHETYPES = [
  { name: "The Precision Striker", icon: "🎯", color: C.red },
  { name: "The Systematic", icon: "⚙️", color: C.blue },
  { name: "The Blitz Trader", icon: "⚡", color: C.orange },
  { name: "The Thesis Builder", icon: "📐", color: C.teal },
  { name: "The Steward", icon: "🛡️", color: C.purple },
  { name: "The Chameleon", icon: "🔄", color: C.cyan },
  { name: "The Contrarian", icon: "🐺", color: C.pink },
  { name: "The Current Rider", icon: "🌊", color: C.green },
  { name: "The Rapid Fire", icon: "💨", color: C.yellow },
  { name: "The Engineer", icon: "🏗️", color: "#6366F1" },
  { name: "The Wildcard", icon: "🃏", color: C.red },
  { name: "The Steady Hand", icon: "🌱", color: C.teal },
  { name: "The FOMO Chaser", icon: "🔥", color: C.orange },
  { name: "The Diamond Hand", icon: "💎", color: C.purple },
  { name: "The Copy Trader", icon: "📡", color: C.cyan },
  { name: "The Professional", icon: "🎖️", color: C.green },
  { name: "The Analyst", icon: "🔬", color: C.blue },
  { name: "The Sentinel", icon: "⚖️", color: C.lime },
  { name: "The Pack Trader", icon: "🐺", color: C.burnt },
  { name: "The Phoenix", icon: "🔥", color: C.red },
];
